// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ParseErrors string
	Reports     string
	TSVFiles    string
	TSVRecords  string
	Units       string
}{
	ParseErrors: "parse_errors",
	Reports:     "reports",
	TSVFiles:    "tsv_files",
	TSVRecords:  "tsv_records",
	Units:       "units",
}
