// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ParseError is an object representing the database table.
type ParseError struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	FileID    null.String `boil:"file_id" json:"file_id,omitempty" toml:"file_id" yaml:"file_id,omitempty"`
	FileName  string      `boil:"file_name" json:"file_name" toml:"file_name" yaml:"file_name"`
	UnitGUID  null.String `boil:"unit_guid" json:"unit_guid,omitempty" toml:"unit_guid" yaml:"unit_guid,omitempty"`
	LineNo    null.Int    `boil:"line_no" json:"line_no,omitempty" toml:"line_no" yaml:"line_no,omitempty"`
	Error     string      `boil:"error" json:"error" toml:"error" yaml:"error"`
	RawLine   null.String `boil:"raw_line" json:"raw_line,omitempty" toml:"raw_line" yaml:"raw_line,omitempty"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *parseErrorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L parseErrorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ParseErrorColumns = struct {
	ID        string
	FileID    string
	FileName  string
	UnitGUID  string
	LineNo    string
	Error     string
	RawLine   string
	CreatedAt string
}{
	ID:        "id",
	FileID:    "file_id",
	FileName:  "file_name",
	UnitGUID:  "unit_guid",
	LineNo:    "line_no",
	Error:     "error",
	RawLine:   "raw_line",
	CreatedAt: "created_at",
}

var ParseErrorTableColumns = struct {
	ID        string
	FileID    string
	FileName  string
	UnitGUID  string
	LineNo    string
	Error     string
	RawLine   string
	CreatedAt string
}{
	ID:        "parse_errors.id",
	FileID:    "parse_errors.file_id",
	FileName:  "parse_errors.file_name",
	UnitGUID:  "parse_errors.unit_guid",
	LineNo:    "parse_errors.line_no",
	Error:     "parse_errors.error",
	RawLine:   "parse_errors.raw_line",
	CreatedAt: "parse_errors.created_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var ParseErrorWhere = struct {
	ID        whereHelperstring
	FileID    whereHelpernull_String
	FileName  whereHelperstring
	UnitGUID  whereHelpernull_String
	LineNo    whereHelpernull_Int
	Error     whereHelperstring
	RawLine   whereHelpernull_String
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperstring{field: "\"parse_errors\".\"id\""},
	FileID:    whereHelpernull_String{field: "\"parse_errors\".\"file_id\""},
	FileName:  whereHelperstring{field: "\"parse_errors\".\"file_name\""},
	UnitGUID:  whereHelpernull_String{field: "\"parse_errors\".\"unit_guid\""},
	LineNo:    whereHelpernull_Int{field: "\"parse_errors\".\"line_no\""},
	Error:     whereHelperstring{field: "\"parse_errors\".\"error\""},
	RawLine:   whereHelpernull_String{field: "\"parse_errors\".\"raw_line\""},
	CreatedAt: whereHelpertime_Time{field: "\"parse_errors\".\"created_at\""},
}

// ParseErrorRels is where relationship names are stored.
var ParseErrorRels = struct {
	File string
}{
	File: "File",
}

// parseErrorR is where relationships are stored.
type parseErrorR struct {
	File *TSVFile `boil:"File" json:"File" toml:"File" yaml:"File"`
}

// NewStruct creates a new relationship struct
func (*parseErrorR) NewStruct() *parseErrorR {
	return &parseErrorR{}
}

func (o *ParseError) GetFile() *TSVFile {
	if o == nil {
		return nil
	}

	return o.R.GetFile()
}

func (r *parseErrorR) GetFile() *TSVFile {
	if r == nil {
		return nil
	}

	return r.File
}

// parseErrorL is where Load methods for each relationship are stored.
type parseErrorL struct{}

var (
	parseErrorAllColumns            = []string{"id", "file_id", "file_name", "unit_guid", "line_no", "error", "raw_line", "created_at"}
	parseErrorColumnsWithoutDefault = []string{"file_name", "error"}
	parseErrorColumnsWithDefault    = []string{"id", "file_id", "unit_guid", "line_no", "raw_line", "created_at"}
	parseErrorPrimaryKeyColumns     = []string{"id"}
	parseErrorGeneratedColumns      = []string{}
)

type (
	// ParseErrorSlice is an alias for a slice of pointers to ParseError.
	// This should almost always be used instead of []ParseError.
	ParseErrorSlice []*ParseError
	// ParseErrorHook is the signature for custom ParseError hook methods
	ParseErrorHook func(context.Context, boil.ContextExecutor, *ParseError) error

	parseErrorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	parseErrorType                 = reflect.TypeOf(&ParseError{})
	parseErrorMapping              = queries.MakeStructMapping(parseErrorType)
	parseErrorPrimaryKeyMapping, _ = queries.BindMapping(parseErrorType, parseErrorMapping, parseErrorPrimaryKeyColumns)
	parseErrorInsertCacheMut       sync.RWMutex
	parseErrorInsertCache          = make(map[string]insertCache)
	parseErrorUpdateCacheMut       sync.RWMutex
	parseErrorUpdateCache          = make(map[string]updateCache)
	parseErrorUpsertCacheMut       sync.RWMutex
	parseErrorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var parseErrorAfterSelectMu sync.Mutex
var parseErrorAfterSelectHooks []ParseErrorHook

var parseErrorBeforeInsertMu sync.Mutex
var parseErrorBeforeInsertHooks []ParseErrorHook
var parseErrorAfterInsertMu sync.Mutex
var parseErrorAfterInsertHooks []ParseErrorHook

var parseErrorBeforeUpdateMu sync.Mutex
var parseErrorBeforeUpdateHooks []ParseErrorHook
var parseErrorAfterUpdateMu sync.Mutex
var parseErrorAfterUpdateHooks []ParseErrorHook

var parseErrorBeforeDeleteMu sync.Mutex
var parseErrorBeforeDeleteHooks []ParseErrorHook
var parseErrorAfterDeleteMu sync.Mutex
var parseErrorAfterDeleteHooks []ParseErrorHook

var parseErrorBeforeUpsertMu sync.Mutex
var parseErrorBeforeUpsertHooks []ParseErrorHook
var parseErrorAfterUpsertMu sync.Mutex
var parseErrorAfterUpsertHooks []ParseErrorHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ParseError) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ParseError) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ParseError) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ParseError) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ParseError) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ParseError) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ParseError) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ParseError) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ParseError) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range parseErrorAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddParseErrorHook registers your hook function for all future operations.
func AddParseErrorHook(hookPoint boil.HookPoint, parseErrorHook ParseErrorHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		parseErrorAfterSelectMu.Lock()
		parseErrorAfterSelectHooks = append(parseErrorAfterSelectHooks, parseErrorHook)
		parseErrorAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		parseErrorBeforeInsertMu.Lock()
		parseErrorBeforeInsertHooks = append(parseErrorBeforeInsertHooks, parseErrorHook)
		parseErrorBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		parseErrorAfterInsertMu.Lock()
		parseErrorAfterInsertHooks = append(parseErrorAfterInsertHooks, parseErrorHook)
		parseErrorAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		parseErrorBeforeUpdateMu.Lock()
		parseErrorBeforeUpdateHooks = append(parseErrorBeforeUpdateHooks, parseErrorHook)
		parseErrorBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		parseErrorAfterUpdateMu.Lock()
		parseErrorAfterUpdateHooks = append(parseErrorAfterUpdateHooks, parseErrorHook)
		parseErrorAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		parseErrorBeforeDeleteMu.Lock()
		parseErrorBeforeDeleteHooks = append(parseErrorBeforeDeleteHooks, parseErrorHook)
		parseErrorBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		parseErrorAfterDeleteMu.Lock()
		parseErrorAfterDeleteHooks = append(parseErrorAfterDeleteHooks, parseErrorHook)
		parseErrorAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		parseErrorBeforeUpsertMu.Lock()
		parseErrorBeforeUpsertHooks = append(parseErrorBeforeUpsertHooks, parseErrorHook)
		parseErrorBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		parseErrorAfterUpsertMu.Lock()
		parseErrorAfterUpsertHooks = append(parseErrorAfterUpsertHooks, parseErrorHook)
		parseErrorAfterUpsertMu.Unlock()
	}
}

// One returns a single parseError record from the query.
func (q parseErrorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ParseError, error) {
	o := &ParseError{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for parse_errors")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ParseError records from the query.
func (q parseErrorQuery) All(ctx context.Context, exec boil.ContextExecutor) (ParseErrorSlice, error) {
	var o []*ParseError

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ParseError slice")
	}

	if len(parseErrorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ParseError records in the query.
func (q parseErrorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count parse_errors rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q parseErrorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if parse_errors exists")
	}

	return count > 0, nil
}

// File pointed to by the foreign key.
func (o *ParseError) File(mods ...qm.QueryMod) tsvFileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FileID),
	}

	queryMods = append(queryMods, mods...)

	return TSVFiles(queryMods...)
}

// LoadFile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (parseErrorL) LoadFile(ctx context.Context, e boil.ContextExecutor, singular bool, maybeParseError interface{}, mods queries.Applicator) error {
	var slice []*ParseError
	var object *ParseError

	if singular {
		var ok bool
		object, ok = maybeParseError.(*ParseError)
		if !ok {
			object = new(ParseError)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeParseError)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeParseError))
			}
		}
	} else {
		s, ok := maybeParseError.(*[]*ParseError)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeParseError)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeParseError))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &parseErrorR{}
		}
		if !queries.IsNil(object.FileID) {
			args[object.FileID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &parseErrorR{}
			}

			if !queries.IsNil(obj.FileID) {
				args[obj.FileID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tsv_files`),
		qm.WhereIn(`tsv_files.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TSVFile")
	}

	var resultSlice []*TSVFile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TSVFile")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tsv_files")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tsv_files")
	}

	if len(tsvFileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.File = foreign
		if foreign.R == nil {
			foreign.R = &tsvFileR{}
		}
		foreign.R.FileParseErrors = append(foreign.R.FileParseErrors, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.FileID, foreign.ID) {
				local.R.File = foreign
				if foreign.R == nil {
					foreign.R = &tsvFileR{}
				}
				foreign.R.FileParseErrors = append(foreign.R.FileParseErrors, local)
				break
			}
		}
	}

	return nil
}

// SetFile of the parseError to the related item.
// Sets o.R.File to related.
// Adds o to related.R.FileParseErrors.
func (o *ParseError) SetFile(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TSVFile) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"parse_errors\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"file_id"}),
		strmangle.WhereClause("\"", "\"", 2, parseErrorPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.FileID, related.ID)
	if o.R == nil {
		o.R = &parseErrorR{
			File: related,
		}
	} else {
		o.R.File = related
	}

	if related.R == nil {
		related.R = &tsvFileR{
			FileParseErrors: ParseErrorSlice{o},
		}
	} else {
		related.R.FileParseErrors = append(related.R.FileParseErrors, o)
	}

	return nil
}

// RemoveFile relationship.
// Sets o.R.File to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ParseError) RemoveFile(ctx context.Context, exec boil.ContextExecutor, related *TSVFile) error {
	var err error

	queries.SetScanner(&o.FileID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("file_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.File = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FileParseErrors {
		if queries.Equal(o.FileID, ri.FileID) {
			continue
		}

		ln := len(related.R.FileParseErrors)
		if ln > 1 && i < ln-1 {
			related.R.FileParseErrors[i] = related.R.FileParseErrors[ln-1]
		}
		related.R.FileParseErrors = related.R.FileParseErrors[:ln-1]
		break
	}
	return nil
}

// ParseErrors retrieves all the records using an executor.
func ParseErrors(mods ...qm.QueryMod) parseErrorQuery {
	mods = append(mods, qm.From("\"parse_errors\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"parse_errors\".*"})
	}

	return parseErrorQuery{q}
}

// FindParseError retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindParseError(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ParseError, error) {
	parseErrorObj := &ParseError{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"parse_errors\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, parseErrorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from parse_errors")
	}

	if err = parseErrorObj.doAfterSelectHooks(ctx, exec); err != nil {
		return parseErrorObj, err
	}

	return parseErrorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ParseError) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no parse_errors provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(parseErrorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	parseErrorInsertCacheMut.RLock()
	cache, cached := parseErrorInsertCache[key]
	parseErrorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			parseErrorAllColumns,
			parseErrorColumnsWithDefault,
			parseErrorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(parseErrorType, parseErrorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(parseErrorType, parseErrorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"parse_errors\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"parse_errors\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into parse_errors")
	}

	if !cached {
		parseErrorInsertCacheMut.Lock()
		parseErrorInsertCache[key] = cache
		parseErrorInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ParseError.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ParseError) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	parseErrorUpdateCacheMut.RLock()
	cache, cached := parseErrorUpdateCache[key]
	parseErrorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			parseErrorAllColumns,
			parseErrorPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update parse_errors, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"parse_errors\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, parseErrorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(parseErrorType, parseErrorMapping, append(wl, parseErrorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update parse_errors row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for parse_errors")
	}

	if !cached {
		parseErrorUpdateCacheMut.Lock()
		parseErrorUpdateCache[key] = cache
		parseErrorUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q parseErrorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for parse_errors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for parse_errors")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ParseErrorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), parseErrorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"parse_errors\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, parseErrorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in parseError slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all parseError")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ParseError) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no parse_errors provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(parseErrorColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	parseErrorUpsertCacheMut.RLock()
	cache, cached := parseErrorUpsertCache[key]
	parseErrorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			parseErrorAllColumns,
			parseErrorColumnsWithDefault,
			parseErrorColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			parseErrorAllColumns,
			parseErrorPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert parse_errors, could not build update column list")
		}

		ret := strmangle.SetComplement(parseErrorAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(parseErrorPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert parse_errors, could not build conflict column list")
			}

			conflict = make([]string, len(parseErrorPrimaryKeyColumns))
			copy(conflict, parseErrorPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"parse_errors\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(parseErrorType, parseErrorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(parseErrorType, parseErrorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert parse_errors")
	}

	if !cached {
		parseErrorUpsertCacheMut.Lock()
		parseErrorUpsertCache[key] = cache
		parseErrorUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ParseError record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ParseError) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ParseError provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), parseErrorPrimaryKeyMapping)
	sql := "DELETE FROM \"parse_errors\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from parse_errors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for parse_errors")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q parseErrorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no parseErrorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from parse_errors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for parse_errors")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ParseErrorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(parseErrorBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), parseErrorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"parse_errors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, parseErrorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from parseError slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for parse_errors")
	}

	if len(parseErrorAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ParseError) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindParseError(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ParseErrorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ParseErrorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), parseErrorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"parse_errors\".* FROM \"parse_errors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, parseErrorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ParseErrorSlice")
	}

	*o = slice

	return nil
}

// ParseErrorExists checks if the ParseError row exists.
func ParseErrorExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"parse_errors\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if parse_errors exists")
	}

	return exists, nil
}

// Exists checks if the ParseError row exists.
func (o *ParseError) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ParseErrorExists(ctx, exec, o.ID)
}
