// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TSVRecord is an object representing the database table.
type TSVRecord struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	FileID    string      `boil:"file_id" json:"file_id" toml:"file_id" yaml:"file_id"`
	UnitGUID  string      `boil:"unit_guid" json:"unit_guid" toml:"unit_guid" yaml:"unit_guid"`
	LineNo    int         `boil:"line_no" json:"line_no" toml:"line_no" yaml:"line_no"`
	MSGID     null.String `boil:"msg_id" json:"msg_id,omitempty" toml:"msg_id" yaml:"msg_id,omitempty"`
	Payload   types.JSON  `boil:"payload" json:"payload" toml:"payload" yaml:"payload"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *tsvRecordR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tsvRecordL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TSVRecordColumns = struct {
	ID        string
	FileID    string
	UnitGUID  string
	LineNo    string
	MSGID     string
	Payload   string
	CreatedAt string
}{
	ID:        "id",
	FileID:    "file_id",
	UnitGUID:  "unit_guid",
	LineNo:    "line_no",
	MSGID:     "msg_id",
	Payload:   "payload",
	CreatedAt: "created_at",
}

var TSVRecordTableColumns = struct {
	ID        string
	FileID    string
	UnitGUID  string
	LineNo    string
	MSGID     string
	Payload   string
	CreatedAt string
}{
	ID:        "tsv_records.id",
	FileID:    "tsv_records.file_id",
	UnitGUID:  "tsv_records.unit_guid",
	LineNo:    "tsv_records.line_no",
	MSGID:     "tsv_records.msg_id",
	Payload:   "tsv_records.payload",
	CreatedAt: "tsv_records.created_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var TSVRecordWhere = struct {
	ID        whereHelperstring
	FileID    whereHelperstring
	UnitGUID  whereHelperstring
	LineNo    whereHelperint
	MSGID     whereHelpernull_String
	Payload   whereHelpertypes_JSON
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperstring{field: "\"tsv_records\".\"id\""},
	FileID:    whereHelperstring{field: "\"tsv_records\".\"file_id\""},
	UnitGUID:  whereHelperstring{field: "\"tsv_records\".\"unit_guid\""},
	LineNo:    whereHelperint{field: "\"tsv_records\".\"line_no\""},
	MSGID:     whereHelpernull_String{field: "\"tsv_records\".\"msg_id\""},
	Payload:   whereHelpertypes_JSON{field: "\"tsv_records\".\"payload\""},
	CreatedAt: whereHelpertime_Time{field: "\"tsv_records\".\"created_at\""},
}

// TSVRecordRels is where relationship names are stored.
var TSVRecordRels = struct {
	File string
}{
	File: "File",
}

// tsvRecordR is where relationships are stored.
type tsvRecordR struct {
	File *TSVFile `boil:"File" json:"File" toml:"File" yaml:"File"`
}

// NewStruct creates a new relationship struct
func (*tsvRecordR) NewStruct() *tsvRecordR {
	return &tsvRecordR{}
}

func (o *TSVRecord) GetFile() *TSVFile {
	if o == nil {
		return nil
	}

	return o.R.GetFile()
}

func (r *tsvRecordR) GetFile() *TSVFile {
	if r == nil {
		return nil
	}

	return r.File
}

// tsvRecordL is where Load methods for each relationship are stored.
type tsvRecordL struct{}

var (
	tsvRecordAllColumns            = []string{"id", "file_id", "unit_guid", "line_no", "msg_id", "payload", "created_at"}
	tsvRecordColumnsWithoutDefault = []string{"file_id", "unit_guid", "line_no", "payload"}
	tsvRecordColumnsWithDefault    = []string{"id", "msg_id", "created_at"}
	tsvRecordPrimaryKeyColumns     = []string{"id"}
	tsvRecordGeneratedColumns      = []string{}
)

type (
	// TSVRecordSlice is an alias for a slice of pointers to TSVRecord.
	// This should almost always be used instead of []TSVRecord.
	TSVRecordSlice []*TSVRecord
	// TSVRecordHook is the signature for custom TSVRecord hook methods
	TSVRecordHook func(context.Context, boil.ContextExecutor, *TSVRecord) error

	tsvRecordQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tsvRecordType                 = reflect.TypeOf(&TSVRecord{})
	tsvRecordMapping              = queries.MakeStructMapping(tsvRecordType)
	tsvRecordPrimaryKeyMapping, _ = queries.BindMapping(tsvRecordType, tsvRecordMapping, tsvRecordPrimaryKeyColumns)
	tsvRecordInsertCacheMut       sync.RWMutex
	tsvRecordInsertCache          = make(map[string]insertCache)
	tsvRecordUpdateCacheMut       sync.RWMutex
	tsvRecordUpdateCache          = make(map[string]updateCache)
	tsvRecordUpsertCacheMut       sync.RWMutex
	tsvRecordUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tsvRecordAfterSelectMu sync.Mutex
var tsvRecordAfterSelectHooks []TSVRecordHook

var tsvRecordBeforeInsertMu sync.Mutex
var tsvRecordBeforeInsertHooks []TSVRecordHook
var tsvRecordAfterInsertMu sync.Mutex
var tsvRecordAfterInsertHooks []TSVRecordHook

var tsvRecordBeforeUpdateMu sync.Mutex
var tsvRecordBeforeUpdateHooks []TSVRecordHook
var tsvRecordAfterUpdateMu sync.Mutex
var tsvRecordAfterUpdateHooks []TSVRecordHook

var tsvRecordBeforeDeleteMu sync.Mutex
var tsvRecordBeforeDeleteHooks []TSVRecordHook
var tsvRecordAfterDeleteMu sync.Mutex
var tsvRecordAfterDeleteHooks []TSVRecordHook

var tsvRecordBeforeUpsertMu sync.Mutex
var tsvRecordBeforeUpsertHooks []TSVRecordHook
var tsvRecordAfterUpsertMu sync.Mutex
var tsvRecordAfterUpsertHooks []TSVRecordHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TSVRecord) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TSVRecord) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TSVRecord) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TSVRecord) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TSVRecord) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TSVRecord) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TSVRecord) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TSVRecord) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TSVRecord) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvRecordAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTSVRecordHook registers your hook function for all future operations.
func AddTSVRecordHook(hookPoint boil.HookPoint, tsvRecordHook TSVRecordHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tsvRecordAfterSelectMu.Lock()
		tsvRecordAfterSelectHooks = append(tsvRecordAfterSelectHooks, tsvRecordHook)
		tsvRecordAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tsvRecordBeforeInsertMu.Lock()
		tsvRecordBeforeInsertHooks = append(tsvRecordBeforeInsertHooks, tsvRecordHook)
		tsvRecordBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tsvRecordAfterInsertMu.Lock()
		tsvRecordAfterInsertHooks = append(tsvRecordAfterInsertHooks, tsvRecordHook)
		tsvRecordAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tsvRecordBeforeUpdateMu.Lock()
		tsvRecordBeforeUpdateHooks = append(tsvRecordBeforeUpdateHooks, tsvRecordHook)
		tsvRecordBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tsvRecordAfterUpdateMu.Lock()
		tsvRecordAfterUpdateHooks = append(tsvRecordAfterUpdateHooks, tsvRecordHook)
		tsvRecordAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tsvRecordBeforeDeleteMu.Lock()
		tsvRecordBeforeDeleteHooks = append(tsvRecordBeforeDeleteHooks, tsvRecordHook)
		tsvRecordBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tsvRecordAfterDeleteMu.Lock()
		tsvRecordAfterDeleteHooks = append(tsvRecordAfterDeleteHooks, tsvRecordHook)
		tsvRecordAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tsvRecordBeforeUpsertMu.Lock()
		tsvRecordBeforeUpsertHooks = append(tsvRecordBeforeUpsertHooks, tsvRecordHook)
		tsvRecordBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tsvRecordAfterUpsertMu.Lock()
		tsvRecordAfterUpsertHooks = append(tsvRecordAfterUpsertHooks, tsvRecordHook)
		tsvRecordAfterUpsertMu.Unlock()
	}
}

// One returns a single tsvRecord record from the query.
func (q tsvRecordQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TSVRecord, error) {
	o := &TSVRecord{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for tsv_records")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TSVRecord records from the query.
func (q tsvRecordQuery) All(ctx context.Context, exec boil.ContextExecutor) (TSVRecordSlice, error) {
	var o []*TSVRecord

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TSVRecord slice")
	}

	if len(tsvRecordAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TSVRecord records in the query.
func (q tsvRecordQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count tsv_records rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tsvRecordQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if tsv_records exists")
	}

	return count > 0, nil
}

// File pointed to by the foreign key.
func (o *TSVRecord) File(mods ...qm.QueryMod) tsvFileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FileID),
	}

	queryMods = append(queryMods, mods...)

	return TSVFiles(queryMods...)
}

// LoadFile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tsvRecordL) LoadFile(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTSVRecord interface{}, mods queries.Applicator) error {
	var slice []*TSVRecord
	var object *TSVRecord

	if singular {
		var ok bool
		object, ok = maybeTSVRecord.(*TSVRecord)
		if !ok {
			object = new(TSVRecord)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTSVRecord)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTSVRecord))
			}
		}
	} else {
		s, ok := maybeTSVRecord.(*[]*TSVRecord)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTSVRecord)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTSVRecord))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tsvRecordR{}
		}
		args[object.FileID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tsvRecordR{}
			}

			args[obj.FileID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tsv_files`),
		qm.WhereIn(`tsv_files.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TSVFile")
	}

	var resultSlice []*TSVFile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TSVFile")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tsv_files")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tsv_files")
	}

	if len(tsvFileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.File = foreign
		if foreign.R == nil {
			foreign.R = &tsvFileR{}
		}
		foreign.R.FileTSVRecords = append(foreign.R.FileTSVRecords, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FileID == foreign.ID {
				local.R.File = foreign
				if foreign.R == nil {
					foreign.R = &tsvFileR{}
				}
				foreign.R.FileTSVRecords = append(foreign.R.FileTSVRecords, local)
				break
			}
		}
	}

	return nil
}

// SetFile of the tsvRecord to the related item.
// Sets o.R.File to related.
// Adds o to related.R.FileTSVRecords.
func (o *TSVRecord) SetFile(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TSVFile) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"tsv_records\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"file_id"}),
		strmangle.WhereClause("\"", "\"", 2, tsvRecordPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FileID = related.ID
	if o.R == nil {
		o.R = &tsvRecordR{
			File: related,
		}
	} else {
		o.R.File = related
	}

	if related.R == nil {
		related.R = &tsvFileR{
			FileTSVRecords: TSVRecordSlice{o},
		}
	} else {
		related.R.FileTSVRecords = append(related.R.FileTSVRecords, o)
	}

	return nil
}

// TSVRecords retrieves all the records using an executor.
func TSVRecords(mods ...qm.QueryMod) tsvRecordQuery {
	mods = append(mods, qm.From("\"tsv_records\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"tsv_records\".*"})
	}

	return tsvRecordQuery{q}
}

// FindTSVRecord retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTSVRecord(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*TSVRecord, error) {
	tsvRecordObj := &TSVRecord{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"tsv_records\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tsvRecordObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from tsv_records")
	}

	if err = tsvRecordObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tsvRecordObj, err
	}

	return tsvRecordObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TSVRecord) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no tsv_records provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tsvRecordColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tsvRecordInsertCacheMut.RLock()
	cache, cached := tsvRecordInsertCache[key]
	tsvRecordInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tsvRecordAllColumns,
			tsvRecordColumnsWithDefault,
			tsvRecordColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tsvRecordType, tsvRecordMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tsvRecordType, tsvRecordMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"tsv_records\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"tsv_records\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into tsv_records")
	}

	if !cached {
		tsvRecordInsertCacheMut.Lock()
		tsvRecordInsertCache[key] = cache
		tsvRecordInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TSVRecord.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TSVRecord) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tsvRecordUpdateCacheMut.RLock()
	cache, cached := tsvRecordUpdateCache[key]
	tsvRecordUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tsvRecordAllColumns,
			tsvRecordPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update tsv_records, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"tsv_records\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, tsvRecordPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tsvRecordType, tsvRecordMapping, append(wl, tsvRecordPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update tsv_records row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for tsv_records")
	}

	if !cached {
		tsvRecordUpdateCacheMut.Lock()
		tsvRecordUpdateCache[key] = cache
		tsvRecordUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tsvRecordQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for tsv_records")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for tsv_records")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TSVRecordSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tsvRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"tsv_records\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, tsvRecordPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in tsvRecord slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all tsvRecord")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TSVRecord) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no tsv_records provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tsvRecordColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tsvRecordUpsertCacheMut.RLock()
	cache, cached := tsvRecordUpsertCache[key]
	tsvRecordUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tsvRecordAllColumns,
			tsvRecordColumnsWithDefault,
			tsvRecordColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tsvRecordAllColumns,
			tsvRecordPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert tsv_records, could not build update column list")
		}

		ret := strmangle.SetComplement(tsvRecordAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(tsvRecordPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert tsv_records, could not build conflict column list")
			}

			conflict = make([]string, len(tsvRecordPrimaryKeyColumns))
			copy(conflict, tsvRecordPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"tsv_records\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(tsvRecordType, tsvRecordMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tsvRecordType, tsvRecordMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert tsv_records")
	}

	if !cached {
		tsvRecordUpsertCacheMut.Lock()
		tsvRecordUpsertCache[key] = cache
		tsvRecordUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TSVRecord record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TSVRecord) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TSVRecord provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tsvRecordPrimaryKeyMapping)
	sql := "DELETE FROM \"tsv_records\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from tsv_records")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for tsv_records")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tsvRecordQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no tsvRecordQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tsv_records")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tsv_records")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TSVRecordSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tsvRecordBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tsvRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"tsv_records\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tsvRecordPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tsvRecord slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tsv_records")
	}

	if len(tsvRecordAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TSVRecord) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTSVRecord(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TSVRecordSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TSVRecordSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tsvRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"tsv_records\".* FROM \"tsv_records\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tsvRecordPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TSVRecordSlice")
	}

	*o = slice

	return nil
}

// TSVRecordExists checks if the TSVRecord row exists.
func TSVRecordExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"tsv_records\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if tsv_records exists")
	}

	return exists, nil
}

// Exists checks if the TSVRecord row exists.
func (o *TSVRecord) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TSVRecordExists(ctx, exec, o.ID)
}
