// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TSVFile is an object representing the database table.
type TSVFile struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	FileName     string      `boil:"file_name" json:"file_name" toml:"file_name" yaml:"file_name"`
	FileSha256   string      `boil:"file_sha256" json:"file_sha256" toml:"file_sha256" yaml:"file_sha256"`
	Status       string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	ErrorMessage null.String `boil:"error_message" json:"error_message,omitempty" toml:"error_message" yaml:"error_message,omitempty"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *tsvFileR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tsvFileL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TSVFileColumns = struct {
	ID           string
	FileName     string
	FileSha256   string
	Status       string
	ErrorMessage string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	FileName:     "file_name",
	FileSha256:   "file_sha256",
	Status:       "status",
	ErrorMessage: "error_message",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var TSVFileTableColumns = struct {
	ID           string
	FileName     string
	FileSha256   string
	Status       string
	ErrorMessage string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "tsv_files.id",
	FileName:     "tsv_files.file_name",
	FileSha256:   "tsv_files.file_sha256",
	Status:       "tsv_files.status",
	ErrorMessage: "tsv_files.error_message",
	CreatedAt:    "tsv_files.created_at",
	UpdatedAt:    "tsv_files.updated_at",
}

// Generated where

var TSVFileWhere = struct {
	ID           whereHelperstring
	FileName     whereHelperstring
	FileSha256   whereHelperstring
	Status       whereHelperstring
	ErrorMessage whereHelpernull_String
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	ID:           whereHelperstring{field: "\"tsv_files\".\"id\""},
	FileName:     whereHelperstring{field: "\"tsv_files\".\"file_name\""},
	FileSha256:   whereHelperstring{field: "\"tsv_files\".\"file_sha256\""},
	Status:       whereHelperstring{field: "\"tsv_files\".\"status\""},
	ErrorMessage: whereHelpernull_String{field: "\"tsv_files\".\"error_message\""},
	CreatedAt:    whereHelpertime_Time{field: "\"tsv_files\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"tsv_files\".\"updated_at\""},
}

// TSVFileRels is where relationship names are stored.
var TSVFileRels = struct {
	FileParseErrors string
	FileTSVRecords  string
}{
	FileParseErrors: "FileParseErrors",
	FileTSVRecords:  "FileTSVRecords",
}

// tsvFileR is where relationships are stored.
type tsvFileR struct {
	FileParseErrors ParseErrorSlice `boil:"FileParseErrors" json:"FileParseErrors" toml:"FileParseErrors" yaml:"FileParseErrors"`
	FileTSVRecords  TSVRecordSlice  `boil:"FileTSVRecords" json:"FileTSVRecords" toml:"FileTSVRecords" yaml:"FileTSVRecords"`
}

// NewStruct creates a new relationship struct
func (*tsvFileR) NewStruct() *tsvFileR {
	return &tsvFileR{}
}

func (o *TSVFile) GetFileParseErrors() ParseErrorSlice {
	if o == nil {
		return nil
	}

	return o.R.GetFileParseErrors()
}

func (r *tsvFileR) GetFileParseErrors() ParseErrorSlice {
	if r == nil {
		return nil
	}

	return r.FileParseErrors
}

func (o *TSVFile) GetFileTSVRecords() TSVRecordSlice {
	if o == nil {
		return nil
	}

	return o.R.GetFileTSVRecords()
}

func (r *tsvFileR) GetFileTSVRecords() TSVRecordSlice {
	if r == nil {
		return nil
	}

	return r.FileTSVRecords
}

// tsvFileL is where Load methods for each relationship are stored.
type tsvFileL struct{}

var (
	tsvFileAllColumns            = []string{"id", "file_name", "file_sha256", "status", "error_message", "created_at", "updated_at"}
	tsvFileColumnsWithoutDefault = []string{"file_name", "file_sha256", "status"}
	tsvFileColumnsWithDefault    = []string{"id", "error_message", "created_at", "updated_at"}
	tsvFilePrimaryKeyColumns     = []string{"id"}
	tsvFileGeneratedColumns      = []string{}
)

type (
	// TSVFileSlice is an alias for a slice of pointers to TSVFile.
	// This should almost always be used instead of []TSVFile.
	TSVFileSlice []*TSVFile
	// TSVFileHook is the signature for custom TSVFile hook methods
	TSVFileHook func(context.Context, boil.ContextExecutor, *TSVFile) error

	tsvFileQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tsvFileType                 = reflect.TypeOf(&TSVFile{})
	tsvFileMapping              = queries.MakeStructMapping(tsvFileType)
	tsvFilePrimaryKeyMapping, _ = queries.BindMapping(tsvFileType, tsvFileMapping, tsvFilePrimaryKeyColumns)
	tsvFileInsertCacheMut       sync.RWMutex
	tsvFileInsertCache          = make(map[string]insertCache)
	tsvFileUpdateCacheMut       sync.RWMutex
	tsvFileUpdateCache          = make(map[string]updateCache)
	tsvFileUpsertCacheMut       sync.RWMutex
	tsvFileUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tsvFileAfterSelectMu sync.Mutex
var tsvFileAfterSelectHooks []TSVFileHook

var tsvFileBeforeInsertMu sync.Mutex
var tsvFileBeforeInsertHooks []TSVFileHook
var tsvFileAfterInsertMu sync.Mutex
var tsvFileAfterInsertHooks []TSVFileHook

var tsvFileBeforeUpdateMu sync.Mutex
var tsvFileBeforeUpdateHooks []TSVFileHook
var tsvFileAfterUpdateMu sync.Mutex
var tsvFileAfterUpdateHooks []TSVFileHook

var tsvFileBeforeDeleteMu sync.Mutex
var tsvFileBeforeDeleteHooks []TSVFileHook
var tsvFileAfterDeleteMu sync.Mutex
var tsvFileAfterDeleteHooks []TSVFileHook

var tsvFileBeforeUpsertMu sync.Mutex
var tsvFileBeforeUpsertHooks []TSVFileHook
var tsvFileAfterUpsertMu sync.Mutex
var tsvFileAfterUpsertHooks []TSVFileHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TSVFile) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TSVFile) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TSVFile) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TSVFile) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TSVFile) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TSVFile) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TSVFile) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TSVFile) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TSVFile) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tsvFileAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTSVFileHook registers your hook function for all future operations.
func AddTSVFileHook(hookPoint boil.HookPoint, tsvFileHook TSVFileHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tsvFileAfterSelectMu.Lock()
		tsvFileAfterSelectHooks = append(tsvFileAfterSelectHooks, tsvFileHook)
		tsvFileAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tsvFileBeforeInsertMu.Lock()
		tsvFileBeforeInsertHooks = append(tsvFileBeforeInsertHooks, tsvFileHook)
		tsvFileBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tsvFileAfterInsertMu.Lock()
		tsvFileAfterInsertHooks = append(tsvFileAfterInsertHooks, tsvFileHook)
		tsvFileAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tsvFileBeforeUpdateMu.Lock()
		tsvFileBeforeUpdateHooks = append(tsvFileBeforeUpdateHooks, tsvFileHook)
		tsvFileBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tsvFileAfterUpdateMu.Lock()
		tsvFileAfterUpdateHooks = append(tsvFileAfterUpdateHooks, tsvFileHook)
		tsvFileAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tsvFileBeforeDeleteMu.Lock()
		tsvFileBeforeDeleteHooks = append(tsvFileBeforeDeleteHooks, tsvFileHook)
		tsvFileBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tsvFileAfterDeleteMu.Lock()
		tsvFileAfterDeleteHooks = append(tsvFileAfterDeleteHooks, tsvFileHook)
		tsvFileAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tsvFileBeforeUpsertMu.Lock()
		tsvFileBeforeUpsertHooks = append(tsvFileBeforeUpsertHooks, tsvFileHook)
		tsvFileBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tsvFileAfterUpsertMu.Lock()
		tsvFileAfterUpsertHooks = append(tsvFileAfterUpsertHooks, tsvFileHook)
		tsvFileAfterUpsertMu.Unlock()
	}
}

// One returns a single tsvFile record from the query.
func (q tsvFileQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TSVFile, error) {
	o := &TSVFile{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for tsv_files")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TSVFile records from the query.
func (q tsvFileQuery) All(ctx context.Context, exec boil.ContextExecutor) (TSVFileSlice, error) {
	var o []*TSVFile

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TSVFile slice")
	}

	if len(tsvFileAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TSVFile records in the query.
func (q tsvFileQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count tsv_files rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tsvFileQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if tsv_files exists")
	}

	return count > 0, nil
}

// FileParseErrors retrieves all the parse_error's ParseErrors with an executor via file_id column.
func (o *TSVFile) FileParseErrors(mods ...qm.QueryMod) parseErrorQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"parse_errors\".\"file_id\"=?", o.ID),
	)

	return ParseErrors(queryMods...)
}

// FileTSVRecords retrieves all the tsv_record's TSVRecords with an executor via file_id column.
func (o *TSVFile) FileTSVRecords(mods ...qm.QueryMod) tsvRecordQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"tsv_records\".\"file_id\"=?", o.ID),
	)

	return TSVRecords(queryMods...)
}

// LoadFileParseErrors allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tsvFileL) LoadFileParseErrors(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTSVFile interface{}, mods queries.Applicator) error {
	var slice []*TSVFile
	var object *TSVFile

	if singular {
		var ok bool
		object, ok = maybeTSVFile.(*TSVFile)
		if !ok {
			object = new(TSVFile)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTSVFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTSVFile))
			}
		}
	} else {
		s, ok := maybeTSVFile.(*[]*TSVFile)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTSVFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTSVFile))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tsvFileR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tsvFileR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`parse_errors`),
		qm.WhereIn(`parse_errors.file_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load parse_errors")
	}

	var resultSlice []*ParseError
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice parse_errors")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on parse_errors")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for parse_errors")
	}

	if len(parseErrorAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FileParseErrors = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &parseErrorR{}
			}
			foreign.R.File = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.FileID) {
				local.R.FileParseErrors = append(local.R.FileParseErrors, foreign)
				if foreign.R == nil {
					foreign.R = &parseErrorR{}
				}
				foreign.R.File = local
				break
			}
		}
	}

	return nil
}

// LoadFileTSVRecords allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tsvFileL) LoadFileTSVRecords(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTSVFile interface{}, mods queries.Applicator) error {
	var slice []*TSVFile
	var object *TSVFile

	if singular {
		var ok bool
		object, ok = maybeTSVFile.(*TSVFile)
		if !ok {
			object = new(TSVFile)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTSVFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTSVFile))
			}
		}
	} else {
		s, ok := maybeTSVFile.(*[]*TSVFile)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTSVFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTSVFile))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tsvFileR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tsvFileR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tsv_records`),
		qm.WhereIn(`tsv_records.file_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tsv_records")
	}

	var resultSlice []*TSVRecord
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tsv_records")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tsv_records")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tsv_records")
	}

	if len(tsvRecordAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FileTSVRecords = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tsvRecordR{}
			}
			foreign.R.File = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FileID {
				local.R.FileTSVRecords = append(local.R.FileTSVRecords, foreign)
				if foreign.R == nil {
					foreign.R = &tsvRecordR{}
				}
				foreign.R.File = local
				break
			}
		}
	}

	return nil
}

// AddFileParseErrors adds the given related objects to the existing relationships
// of the tsv_file, optionally inserting them as new records.
// Appends related to o.R.FileParseErrors.
// Sets related.R.File appropriately.
func (o *TSVFile) AddFileParseErrors(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ParseError) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.FileID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"parse_errors\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"file_id"}),
				strmangle.WhereClause("\"", "\"", 2, parseErrorPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.FileID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &tsvFileR{
			FileParseErrors: related,
		}
	} else {
		o.R.FileParseErrors = append(o.R.FileParseErrors, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &parseErrorR{
				File: o,
			}
		} else {
			rel.R.File = o
		}
	}
	return nil
}

// SetFileParseErrors removes all previously related items of the
// tsv_file replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.File's FileParseErrors accordingly.
// Replaces o.R.FileParseErrors with related.
// Sets related.R.File's FileParseErrors accordingly.
func (o *TSVFile) SetFileParseErrors(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ParseError) error {
	query := "update \"parse_errors\" set \"file_id\" = null where \"file_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.FileParseErrors {
			queries.SetScanner(&rel.FileID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.File = nil
		}
		o.R.FileParseErrors = nil
	}

	return o.AddFileParseErrors(ctx, exec, insert, related...)
}

// RemoveFileParseErrors relationships from objects passed in.
// Removes related items from R.FileParseErrors (uses pointer comparison, removal does not keep order)
// Sets related.R.File.
func (o *TSVFile) RemoveFileParseErrors(ctx context.Context, exec boil.ContextExecutor, related ...*ParseError) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.FileID, nil)
		if rel.R != nil {
			rel.R.File = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("file_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.FileParseErrors {
			if rel != ri {
				continue
			}

			ln := len(o.R.FileParseErrors)
			if ln > 1 && i < ln-1 {
				o.R.FileParseErrors[i] = o.R.FileParseErrors[ln-1]
			}
			o.R.FileParseErrors = o.R.FileParseErrors[:ln-1]
			break
		}
	}

	return nil
}

// AddFileTSVRecords adds the given related objects to the existing relationships
// of the tsv_file, optionally inserting them as new records.
// Appends related to o.R.FileTSVRecords.
// Sets related.R.File appropriately.
func (o *TSVFile) AddFileTSVRecords(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TSVRecord) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FileID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"tsv_records\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"file_id"}),
				strmangle.WhereClause("\"", "\"", 2, tsvRecordPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FileID = o.ID
		}
	}

	if o.R == nil {
		o.R = &tsvFileR{
			FileTSVRecords: related,
		}
	} else {
		o.R.FileTSVRecords = append(o.R.FileTSVRecords, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tsvRecordR{
				File: o,
			}
		} else {
			rel.R.File = o
		}
	}
	return nil
}

// TSVFiles retrieves all the records using an executor.
func TSVFiles(mods ...qm.QueryMod) tsvFileQuery {
	mods = append(mods, qm.From("\"tsv_files\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"tsv_files\".*"})
	}

	return tsvFileQuery{q}
}

// FindTSVFile retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTSVFile(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*TSVFile, error) {
	tsvFileObj := &TSVFile{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"tsv_files\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tsvFileObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from tsv_files")
	}

	if err = tsvFileObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tsvFileObj, err
	}

	return tsvFileObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TSVFile) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no tsv_files provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tsvFileColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tsvFileInsertCacheMut.RLock()
	cache, cached := tsvFileInsertCache[key]
	tsvFileInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tsvFileAllColumns,
			tsvFileColumnsWithDefault,
			tsvFileColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tsvFileType, tsvFileMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tsvFileType, tsvFileMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"tsv_files\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"tsv_files\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into tsv_files")
	}

	if !cached {
		tsvFileInsertCacheMut.Lock()
		tsvFileInsertCache[key] = cache
		tsvFileInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TSVFile.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TSVFile) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tsvFileUpdateCacheMut.RLock()
	cache, cached := tsvFileUpdateCache[key]
	tsvFileUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tsvFileAllColumns,
			tsvFilePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update tsv_files, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"tsv_files\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, tsvFilePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tsvFileType, tsvFileMapping, append(wl, tsvFilePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update tsv_files row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for tsv_files")
	}

	if !cached {
		tsvFileUpdateCacheMut.Lock()
		tsvFileUpdateCache[key] = cache
		tsvFileUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tsvFileQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for tsv_files")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for tsv_files")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TSVFileSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tsvFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"tsv_files\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, tsvFilePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in tsvFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all tsvFile")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TSVFile) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no tsv_files provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tsvFileColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tsvFileUpsertCacheMut.RLock()
	cache, cached := tsvFileUpsertCache[key]
	tsvFileUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tsvFileAllColumns,
			tsvFileColumnsWithDefault,
			tsvFileColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tsvFileAllColumns,
			tsvFilePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert tsv_files, could not build update column list")
		}

		ret := strmangle.SetComplement(tsvFileAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(tsvFilePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert tsv_files, could not build conflict column list")
			}

			conflict = make([]string, len(tsvFilePrimaryKeyColumns))
			copy(conflict, tsvFilePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"tsv_files\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(tsvFileType, tsvFileMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tsvFileType, tsvFileMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert tsv_files")
	}

	if !cached {
		tsvFileUpsertCacheMut.Lock()
		tsvFileUpsertCache[key] = cache
		tsvFileUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TSVFile record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TSVFile) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TSVFile provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tsvFilePrimaryKeyMapping)
	sql := "DELETE FROM \"tsv_files\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from tsv_files")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for tsv_files")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tsvFileQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no tsvFileQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tsv_files")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tsv_files")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TSVFileSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tsvFileBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tsvFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"tsv_files\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tsvFilePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tsvFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tsv_files")
	}

	if len(tsvFileAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TSVFile) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTSVFile(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TSVFileSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TSVFileSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tsvFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"tsv_files\".* FROM \"tsv_files\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tsvFilePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TSVFileSlice")
	}

	*o = slice

	return nil
}

// TSVFileExists checks if the TSVFile row exists.
func TSVFileExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"tsv_files\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if tsv_files exists")
	}

	return exists, nil
}

// Exists checks if the TSVFile row exists.
func (o *TSVFile) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TSVFileExists(ctx, exec, o.ID)
}
